services:
  swag:
    image: linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      PUID: ${PUID}
      GUID: ${PGID}
      TZ: ${TZ}
      URL: ${DOMAIN}
      EMAIL: admin@${DOMAIN}
      VALIDATION: dns
      DNSPLUGIN: cloudflare
      SUBDOMAINS: jenkins
      ONLY_SUBDOMAINS: 'true'
    volumes:
      - swag:/config
      - ./jenkins.subdomain.conf:/config/nginx/proxy-confs/jenkins.subdomain.conf
      - ./cloudflare.ini:/config/dns-conf/cloudflare.ini
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
    networks:
      - jenkins

  jenkins:
    image: ofersadan85/jenkins-docker-master
    container_name: jenkins
    environment:
      JENKINS_USER: ${JENKINS_USER}
      JENKINS_PASS: ${JENKINS_PASS}
      JAVA_OPTS: -Djenkins.install.runSetupWizard=false
      DOCKER_TLS_CERTDIR: /certs
    # ports:
    #   - 8080:8080
    #   - 50000:50000
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-certs:/certs/client
      - ./master/plugins:/var/jenkins_home/plugins
      - ./master/init.groovy.d:/usr/share/jenkins/ref/init.groovy.d
    networks:
      - jenkins
    restart: always

  socat:
    image: alpine/socat
    container_name: socat
    command: tcp-listen:2375,fork,reuseaddr unix-connect:/var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins

volumes:
  swag:
  jenkins-data:
  jenkins-certs:


networks:
  jenkins:
